### ISSUE TITLE
ts-router tamplate not working

### ISSUE THREAD

**Issue by mztlive** [solidjs/templates#97]
Uncaught TypeError: route.outlet is not a function
    at get children [as children] (components.jsx:65:68)
    at Object.fn (dev.js:995:35)
    at runComputation (dev.js:696:22)
    at updateComputation (dev.js:679:3)
    at createMemo (dev.js:250:10)
    at children (dev.js:577:20)
    at dev.js:995:14
    at untrack (dev.js:434:12)
    at Object.fn (dev.js:991:36)
    at runComputation (dev.js:696:22)

**Comment by LadyBluenotes** [comment]
#95 Is the proposed fix for this issue.

**Comment by amoutonbrady** [comment]
I merged the PR, thanks for raising the issue!
